'''empty message

Revision ID: 6e6047a98a18
Revises:
Create Date: 2024-05-08 14:52:39.779144

'''

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6e6047a98a18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'url_map',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('original', sa.String(length=512), nullable=False),
        sa.Column('short', sa.String(length=16), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('short'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_map')
    # ### end Alembic commands ###
